project_name: yey
builds:
  - dir: src
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -X "main.version=v{{ .Version }}"
archives:
  - format: tar.gz
    wrap_in_directory: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: silphid
      name: homebrew-tap
    homepage: "https://github.com/silphid/yey"
    description: "An interactive, human-friendly docker launcher for dev and devops"
    license: "MIT"
